In [3]:
import numpy as np
list_ = ['1','2','3','4','5']
array_list = np.array(object = list_)

In [4]:
#Q.1 Ans:-

print(list_)
# This the a normal list that we use in python
# It's data types is <class 'list'>
# No new library is required for this
print(type(list_))

['1', '2', '3', '4', '5']
<class 'list'>


In [5]:
print(array_list)
# This is an numpy array
# It's data types is <class 'numpy.ndarray'>
# We need to import numpy to use this
print(type(array_list))

['1' '2' '3' '4' '5']
<class 'numpy.ndarray'>


In [6]:
#Q.2 Ans:-

# array_list
array_list.dtype

dtype('<U1')

In [7]:
for i in array_list: print(type(i))

<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


In [8]:
# list_
for i in list_: print(type(i))

<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>


In [9]:
#Q.3 Ans:-

array_list = np.array(object = list_, dtype = int)

In [10]:
array_list.dtype
# This types has been changes form Str(Unicode string) to Integer

dtype('int64')

In [12]:
#Consider the below code to answer further questions:
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)
num_array

array([[1, 2, 3],
       [4, 5, 6]])

In [13]:
#Q.4 Ans:-
# (i) shape
num_array.shape

(2, 3)

In [14]:
# (ii) size
num_array.size

6

In [15]:
#Q.5 Ans:-

np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [16]:
np.matrix(np.zeros((3,3)))

matrix([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [19]:
#Q.6  Ans:-

np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [20]:
np.matrix(np.eye(5))

matrix([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])